---
title: "Introducing Michelle"
author: "Michelle Coen"
output: html_document
---

About Me
===================
Hi everyone! My name is Michelle Coen. I am a second year MHS ID Epi student living here in Baltimore. I specialize in sexual health and wellness and am currently working with gonorrhea and syphilis data in Baltimore City. I am from Phoenix, Arizona and I earned my BA from Arizona State University.

My experience with R includes statistical courses for year one of the MHS program, practice in the Epidemiology of Infectious Diseases class, and some slight use of R for work. My understanding and use of R is pretty limited - I am excited to become more fluent in the program because I will be using it for the rest of my career.

Five Fun Facts About Me
-------------------
1. I love to roller skate - catch me at the roller rink on Thursday nights
2. My happy place is Target - I like to wander the aisles sobbing while drinking a slushee
3. All of my parents are teachers
4. I worked in Chennai, India
5. I played quidditch in my undergrad - yes I'm serious, no we do not fly

Something Interesting
-------------------
If you read my fun facts, you know I played quidditch. Though nothing can compare to the chaos of being in person, I have provided you a link to watch a game my team played at regionals my junior year - super weird, incredibly fun, most injuries of all club sports at ASU :)
[https://youtu.be/RfQtv4McidA]


